# Generated by Django 4.2.11 on 2024-06-21 13:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.CharField(max_length=256, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=256)),
                ("hours", models.IntegerField()),
                (
                    "kind",
                    models.IntegerField(choices=[(1, "本科生课程"), (2, "研究生课程")]),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Paper",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=256)),
                ("pub_sourse", models.CharField(max_length=256)),
                ("pub_year", models.DateField()),
                (
                    "kind",
                    models.IntegerField(
                        choices=[
                            (1, "full paper"),
                            (2, "short paper"),
                            (3, "poster paper"),
                            (4, "demo paper"),
                        ]
                    ),
                ),
                (
                    "level",
                    models.IntegerField(
                        choices=[
                            (1, "CCF-A"),
                            (2, "CCF-B"),
                            (3, "CCF-C"),
                            (4, "中文 CCF-A"),
                            (5, "中文 CCF-B"),
                            (6, "无级别"),
                        ]
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.CharField(max_length=256, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=256)),
                ("source", models.CharField(max_length=256)),
                ("kind", models.IntegerField()),
                ("total_fund", models.FloatField()),
                ("start_year", models.IntegerField()),
                ("end_year", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Teacher",
            fields=[
                (
                    "id",
                    models.CharField(max_length=5, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=200)),
                ("gender", models.IntegerField(choices=[(1, "男"), (2, "女")])),
                (
                    "title",
                    models.IntegerField(
                        choices=[
                            (1, "博士后"),
                            (2, "助教"),
                            (3, "讲师"),
                            (4, "副教授"),
                            (5, "特任教授"),
                            (6, "教授"),
                            (7, "助理研究员"),
                            (8, "特任副研究员"),
                            (9, "副研究员"),
                            (10, "特任研究员"),
                            (11, "研究员"),
                        ]
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TeacherProject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rank", models.IntegerField()),
                ("fund", models.FloatField()),
                (
                    "project_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="teacher_app.project",
                    ),
                ),
                (
                    "teacher_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="teacher_app.teacher",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TeacherPaper",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rank", models.IntegerField()),
                ("corresp", models.BooleanField()),
                (
                    "paper_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="teacher_app.paper",
                    ),
                ),
                (
                    "teacher_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="teacher_app.teacher",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TeacherCourse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.IntegerField()),
                (
                    "semester",
                    models.IntegerField(
                        choices=[(1, "春季学期"), (2, "夏季学期"), (3, "秋季学期")]
                    ),
                ),
                ("hour", models.IntegerField()),
                (
                    "course_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="teacher_app.course",
                    ),
                ),
                (
                    "teacher_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="teacher_app.teacher",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="project",
            name="teachers",
            field=models.ManyToManyField(
                through="teacher_app.TeacherProject", to="teacher_app.teacher"
            ),
        ),
        migrations.AddField(
            model_name="paper",
            name="teachers",
            field=models.ManyToManyField(
                through="teacher_app.TeacherPaper", to="teacher_app.teacher"
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="teachers",
            field=models.ManyToManyField(
                through="teacher_app.TeacherCourse", to="teacher_app.teacher"
            ),
        ),
        migrations.AddConstraint(
            model_name="teacherproject",
            constraint=models.UniqueConstraint(
                fields=("teacher_id", "project_id"), name="unique_teacher_project"
            ),
        ),
        migrations.AddConstraint(
            model_name="teacherpaper",
            constraint=models.UniqueConstraint(
                fields=("teacher_id", "paper_id"), name="unique_teacher_paper"
            ),
        ),
        migrations.AddConstraint(
            model_name="teachercourse",
            constraint=models.UniqueConstraint(
                fields=("teacher_id", "course_id"), name="unique_teacher_course"
            ),
        ),
    ]
