# Generated by Django 5.0.6 on 2024-06-21 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("teacher_app", "0001_initial"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="teachercourse",
            name="unique_teacher_course",
        ),
        migrations.RemoveConstraint(
            model_name="teacherpaper",
            name="unique_teacher_paper",
        ),
        migrations.RemoveConstraint(
            model_name="teacherproject",
            name="unique_teacher_project",
        ),
        migrations.RenameField(
            model_name="teachercourse",
            old_name="course_id",
            new_name="course",
        ),
        migrations.RenameField(
            model_name="teachercourse",
            old_name="teacher_id",
            new_name="teacher",
        ),
        migrations.RenameField(
            model_name="teacherpaper",
            old_name="paper_id",
            new_name="paper",
        ),
        migrations.RenameField(
            model_name="teacherpaper",
            old_name="teacher_id",
            new_name="teacher",
        ),
        migrations.RenameField(
            model_name="teacherproject",
            old_name="project_id",
            new_name="project",
        ),
        migrations.RenameField(
            model_name="teacherproject",
            old_name="teacher_id",
            new_name="teacher",
        ),
        migrations.AddConstraint(
            model_name="teachercourse",
            constraint=models.UniqueConstraint(
                fields=("teacher", "course"), name="unique_teacher_course"
            ),
        ),
        migrations.AddConstraint(
            model_name="teacherpaper",
            constraint=models.UniqueConstraint(
                fields=("teacher", "paper"), name="unique_teacher_paper"
            ),
        ),
        migrations.AddConstraint(
            model_name="teacherproject",
            constraint=models.UniqueConstraint(
                fields=("teacher", "project"), name="unique_teacher_project"
            ),
        ),
    ]
