# Generated by Django 5.0.6 on 2024-06-21 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("teacher_app", "0002_remove_teachercourse_unique_teacher_course_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="kind",
            field=models.IntegerField(
                choices=[
                    (1, "国家级项目"),
                    (2, "省部级项目"),
                    (3, "市厅级项目"),
                    (4, "企业合作项目"),
                    (5, "其它类型项目"),
                ]
            ),
        ),
    ]
